# Generated by Django 6.0.4 on 2026-06-18 13:10

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название устройства')),
                ('device_type', models.CharField(choices=[('light', 'Свет'), ('tv', 'Телевизор'), ('ac', 'Кондиционер'), ('coffee', 'Кофемашина'), ('washer', 'Стиральная машина'), ('socket', 'Розетка')], max_length=20, verbose_name='Тип устройства')),
                ('status', models.CharField(choices=[('on', 'Включено'), ('off', 'Выключено'), ('standby', 'Ожидание'), ('error', 'Ошибка'), ('maintenance', 'Обслуживание')], default='off', max_length=20, verbose_name='Статус')),
                ('is_online', models.BooleanField(default=True, verbose_name='В сети')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP-адрес')),
                ('mac_address', models.CharField(blank=True, max_length=17, verbose_name='MAC-адрес')),
                ('firmware_version', models.CharField(default='1.0.0', max_length=20, verbose_name='Версия прошивки')),
                ('last_seen', models.DateTimeField(auto_now=True, verbose_name='Последний раз в сети')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Устройство',
                'verbose_name_plural': 'Устройства',
                'ordering': ['room', 'device_type', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название комнаты')),
                ('room_type', models.CharField(choices=[('living_room', 'Гостиная'), ('bedroom', 'Спальня'), ('kitchen', 'Кухня'), ('bathroom', 'Санузел'), ('hallway', 'Прихожая'), ('study', 'Кабинет')], max_length=20, verbose_name='Тип комнаты')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('floor', models.IntegerField(default=1, verbose_name='Этаж')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Комната',
                'verbose_name_plural': 'Комнаты',
                'ordering': ['floor', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ACDevice',
            fields=[
                ('device_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='devices.device')),
                ('temperature', models.IntegerField(default=22, validators=[django.core.validators.MinValueValidator(16), django.core.validators.MaxValueValidator(30)], verbose_name='Температура (°C)')),
                ('mode', models.CharField(choices=[('cool', 'Охлаждение'), ('heat', 'Обогрев'), ('fan', 'Вентиляция'), ('dry', 'Осушение'), ('auto', 'Авто')], default='auto', max_length=20, verbose_name='Режим')),
                ('fan_speed', models.IntegerField(default=50, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Скорость вентилятора (%)')),
                ('swing', models.BooleanField(default=False, verbose_name='Автоповорот жалюзи')),
            ],
            options={
                'verbose_name': 'Кондиционер',
                'verbose_name_plural': 'Кондиционеры',
            },
            bases=('devices.device',),
        ),
        migrations.CreateModel(
            name='CoffeeMachine',
            fields=[
                ('device_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='devices.device')),
                ('water_level', models.IntegerField(default=80, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Уровень воды (%)')),
                ('beans_level', models.IntegerField(default=70, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Уровень зерен (%)')),
                ('strength', models.CharField(choices=[('weak', 'Слабая'), ('medium', 'Средняя'), ('strong', 'Крепкая')], default='medium', max_length=20, verbose_name='Крепость')),
                ('size', models.CharField(choices=[('small', 'Маленькая'), ('medium', 'Средняя'), ('large', 'Большая')], default='medium', max_length=20, verbose_name='Размер порции')),
                ('is_cleaning', models.BooleanField(default=False, verbose_name='Очистка')),
            ],
            options={
                'verbose_name': 'Кофемашина',
                'verbose_name_plural': 'Кофемашины',
            },
            bases=('devices.device',),
        ),
        migrations.CreateModel(
            name='LightDevice',
            fields=[
                ('device_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='devices.device')),
                ('brightness', models.IntegerField(default=100, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Яркость (%)')),
                ('color_temperature', models.IntegerField(default=3000, validators=[django.core.validators.MinValueValidator(2000), django.core.validators.MaxValueValidator(6500)], verbose_name='Цветовая температура (K)')),
                ('is_dimmable', models.BooleanField(default=True, verbose_name='С регулировкой яркости')),
                ('is_rgb', models.BooleanField(default=False, verbose_name='Цветной свет')),
                ('schedule_on', models.TimeField(blank=True, null=True, verbose_name='Время включения')),
                ('schedule_off', models.TimeField(blank=True, null=True, verbose_name='Время выключения')),
            ],
            options={
                'verbose_name': 'Освещение',
                'verbose_name_plural': 'Освещение',
            },
            bases=('devices.device',),
        ),
        migrations.CreateModel(
            name='SocketDevice',
            fields=[
                ('device_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='devices.device')),
                ('power_consumption', models.FloatField(default=0, verbose_name='Потребляемая мощность (Вт)')),
                ('voltage', models.FloatField(default=220, verbose_name='Напряжение (В)')),
                ('current', models.FloatField(default=0, verbose_name='Ток (А)')),
                ('is_child_lock', models.BooleanField(default=False, verbose_name='Защита от детей')),
            ],
            options={
                'verbose_name': 'Розетка',
                'verbose_name_plural': 'Розетки',
            },
            bases=('devices.device',),
        ),
        migrations.CreateModel(
            name='TVDevice',
            fields=[
                ('device_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='devices.device')),
                ('volume', models.IntegerField(default=50, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Громкость (%)')),
                ('channel', models.IntegerField(default=1, verbose_name='Канал')),
                ('input_source', models.CharField(default='HDMI 1', max_length=50, verbose_name='Источник сигнала')),
                ('is_muted', models.BooleanField(default=False, verbose_name='Звук выключен')),
            ],
            options={
                'verbose_name': 'Телевизор',
                'verbose_name_plural': 'Телевизоры',
            },
            bases=('devices.device',),
        ),
        migrations.CreateModel(
            name='WasherDevice',
            fields=[
                ('device_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='devices.device')),
                ('program', models.CharField(choices=[('cotton', 'Хлопок'), ('synthetic', 'Синтетика'), ('delicate', 'Деликатная'), ('quick', 'Быстрая'), ('wool', 'Шерсть')], default='cotton', max_length=20, verbose_name='Программа')),
                ('temperature', models.IntegerField(default=40, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(95)], verbose_name='Температура (°C)')),
                ('spin_speed', models.IntegerField(default=800, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1400)], verbose_name='Скорость отжима (об/мин)')),
                ('time_remaining', models.IntegerField(default=0, verbose_name='Осталось минут')),
                ('is_running', models.BooleanField(default=False, verbose_name='Работает')),
            ],
            options={
                'verbose_name': 'Стиральная машина',
                'verbose_name_plural': 'Стиральные машины',
            },
            bases=('devices.device',),
        ),
        migrations.CreateModel(
            name='DeviceLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=200, verbose_name='Действие')),
                ('old_status', models.CharField(blank=True, max_length=20, verbose_name='Старый статус')),
                ('new_status', models.CharField(blank=True, max_length=20, verbose_name='Новый статус')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP-адрес')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата и время')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='devices.device')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Лог устройства',
                'verbose_name_plural': 'Логи устройств',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='device',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devices', to='devices.room', verbose_name='Комната'),
        ),
        migrations.CreateModel(
            name='Scene',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название сценария')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scenes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Сценарий',
                'verbose_name_plural': 'Сценарии',
            },
        ),
        migrations.CreateModel(
            name='SceneDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_status', models.CharField(default='on', max_length=20, verbose_name='Целевой статус')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='devices.device')),
                ('scene', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='devices.scene')),
            ],
            options={
                'verbose_name': 'Устройство в сценарии',
                'verbose_name_plural': 'Устройства в сценариях',
                'unique_together': {('scene', 'device')},
            },
        ),
        migrations.AddField(
            model_name='scene',
            name='devices',
            field=models.ManyToManyField(related_name='scenes', through='devices.SceneDevice', to='devices.device'),
        ),
    ]
